### ISSUE TITLE
Invalid data for release id when trying to update a component group with PUT

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#266]
At https://pdc.stg.fedoraproject.org/, I'm trying to update an existing component group with a ``PUT`` call, but am failing with this traceback:

```python
[2016-01-25 15:35:11][pdcupdater.commands   ERROR] {"invalid_data":"fedora-24-fedora-NEXT","detail":"Not found.","id_of_invalid_data":"release"}
Traceback (most recent call last):
  File "/home/threebean/devel/pdc-updater/pdcupdater/commands.py", line 56, in initialize
    handler.initialize(pdc)
  File "/home/threebean/devel/pdc-updater/pdcupdater/handlers/atomic.py", line 84, in initialize
    self._update_atomic_component_group(pdc, component_group)
  File "/home/threebean/devel/pdc-updater/pdcupdater/handlers/atomic.py", line 94, in _update_atomic_component_group
    pdc['component-groups']._ = component_group
  File "<string>", line 1, in <lambda>
  File "/home/threebean/.virtualenvs/pdc-updater/lib/python2.7/site-packages/beanbag/namespace.py", line 149, in fn
    return basefn(getattr(self, ".base"), getattr(self, ".path"), attr, *args, **kwargs)
  File "/home/threebean/.virtualenvs/pdc-updater/lib/python2.7/site-packages/beanbag/namespace.py", line 305, in setattr
    return self._set(self._get(path, self.attr(attr)), val)
  File "/home/threebean/.virtualenvs/pdc-updater/lib/python2.7/site-packages/beanbag/namespace.py", line 301, in _set
    return self.set(path, val)
  File "/home/threebean/.virtualenvs/pdc-updater/lib/python2.7/site-packages/beanbag/url_v1.py", line 114, in set
    return self.make_request(path, "PUT", {}, val)
  File "/home/threebean/.virtualenvs/pdc-updater/lib/python2.7/site-packages/beanbag/url_v1.py", line 155, in make_request
    "Bad response code: %d" % r.status_code)
BeanBagException: Bad response code: 404
```

If you check some of the other endpoints, you'll see that that release_id does exist:

```json
{
    "count": 7,
    "next": null,
    "previous": null,
    "results": [
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora EPEL",
            "product_version": null,
            "release_id": "epel-5-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "epel",
            "version": "5"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora EPEL",
            "product_version": null,
            "release_id": "epel-6-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "epel",
            "version": "6"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora EPEL",
            "product_version": null,
            "release_id": "epel-7-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "epel",
            "version": "7"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora",
            "product_version": null,
            "release_id": "fedora-21-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "fedora",
            "version": "21"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora",
            "product_version": null,
            "release_id": "fedora-22-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "fedora",
            "version": "22"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora",
            "product_version": null,
            "release_id": "fedora-23-fedora-NEXT-updates",
            "release_type": "updates",
            "short": "fedora",
            "version": "23"
        },
        {
            "active": true,
            "base_product": "fedora-NEXT",
            "bugzilla": null,
            "compose_set": [],
            "dist_git": null,
            "integrated_with": null,
            "name": "Fedora",
            "product_version": null,
            "release_id": "fedora-24-fedora-NEXT",
            "release_type": "ga",
            "short": "fedora",
            "version": "24"
        }
    ]
}
```

and also that the component group exists, with the correct release_id:

```json

{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "components": [],
            "description": "Deps for atomic-docker-host https://git.fedorahosted.org/cgit/fedora-atomic.git",
            "group_type": "atomic-docker-host",
            "id": 1,
            "release": "fedora-24-fedora-NEXT"
        },
        {
            "components": [],
            "description": "Deps for atomic-docker-host https://git.fedorahosted.org/cgit/fedora-atomic.git/plain/",
            "group_type": "atomic-docker-host",
            "id": 2,
            "release": "fedora-24-fedora-NEXT"
        }
    ]
}
```

Any ideas on what I'm missing here?  Or, is it a bug in PDC?

**Comment by ralphbean** [comment]
FYI, the code I'm working on is in [this commit](https://github.com/fedora-infra/pdc-updater/commit/58ad331961c5a42cd442555139ccd0459afca5ba).

**Comment by lubomir** [comment]
The problem is [in this line](https://github.com/fedora-infra/pdc-updater/blob/58ad331961c5a42cd442555139ccd0459afca5ba/pdcupdater/handlers/atomic.py#L94). It performs the PUT request not on a specific group, but on the list URL. PDC interprets that as a bulk update, but the data does not match that. It should be

```python
pdc['component-groups'][group_pk]._ = component_group
```

The question is how to actually get the identifier. You could ask for all groups with given type and release, but there may be more of them (each with different description), and there is no filter for description. You could iterate over them and find the correct one, but that hardly seems like a nice solution.

**Comment by ralphbean** [comment]
Thanks @lubomir.  I'll do the ugly "iterate and find" approach for now to get things working until we can sort out #265.

**Comment by sochotnicky** [comment]
I am trying to figure out if there's anything for us to do here given that #265 can't be fixed without breaking API stability. And this was just wrong use of the API. I'd say listing by release and group type should be fine (+ sort of asserting that there's only one such group). That will give you one exact group to edit. 

Do I get that right?

**Comment by ralphbean** [comment]
No, nothing to do here.  Thanks @sochotnicky and @lubomir!
