### ISSUE TITLE
400 error when trying to import compose

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#289]
This is one of two separate, but perhaps related tickets.

When trying to import some of our recent Fedora composes, I get the following error:

```python
[2016-02-29 15:01:30][pdcupdater.handlers.compose   ERROR]
    Failed to import
    u'http://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20160226.n.0'
    u'https://pdc.fedoraproject.org/rest_api/v1/compose-images/'
    u'{"detail":["This field cannot be null."]}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pdcupdater/handlers/compose.py", line 76, in initialize
    self._import_compose(pdc, compose_id, url)
  File "/usr/lib/python2.7/site-packages/pdcupdater/handlers/compose.py", line 128, in _import_compose
    image_manifest=images,
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python2.7/site-packages/beanbag/namespace.py", line 131, in fn
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beanbag/url_v1.py", line 102, in call
    return self.make_request(path, verb, kwargs, body)
  File "/usr/lib/python2.7/site-packages/beanbag/url_v1.py", line 155, in make_request
    "Bad response code: %d" % (r.status_code,))
BeanBagException: Bad response code: 400
```

You can see the URLs there for the compose metadata.  Is there something wrong with the metadata of http://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20160226.n.0 itself?  Or is there something wrong with PDC's handling of that?

The error message is not very helpful.  "This field cannot be null"  Which field should not be null?

Please let me know if I can provide any other info.

**Comment by lubomir** [comment]
I believe the field in question is `implant_md5`, which really only makes sense for ISOs. The manifest contains a docker image that does not have it. It is fixed by 8a4eb0d196c46c873a33675. I'm not sure if an easy workaround exists, the field is enforced to not be empty on the database level.

**Comment by ralphbean** [comment]
Thanks for the pointer to 8a4eb0d.  I applied it locally to our instance.

**Comment by ralphbean** [comment]
This is solved for us now.  Thanks!
