### ISSUE TITLE
virtualenv - not working "out of the box"

### ISSUE THREAD

**Issue by matysek** [product-definition-center/product-definition-center#353]
How to reproduce:
* create virtualenv and install dependencies
```
$ virtualenv env
$ source env/bin/activate
$ pip install requirements/devel.txt
```
* run django tests and many of them will fail because of  some missing imports
```
$ make test
```
* I get failure like this:
```
(env)➜  product-definition-center git:(master) ✗ make test
python manage.py test --settings pdc.settings_test pdc contrib
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/Projects/product-definition-center/pdc/apps/package/models.py", line 18, in <module>
    from kobo.rpmlib import parse_nvra
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/kobo/rpmlib.py", line 15, in <module>
    import koji
ImportError: No module named koji
Makefile:21: recipe for target 'test' failed
make: *** [test] Error 1
```

Other notes:
*  when using the option `--system-site-packages` I get this output::
```
======================================================================
ERROR: test_update_sigkey (pdc.apps.common.tests.SigKeyRESTTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/Projects/product-definition-center/pdc/apps/common/tests.py", line 347, in test_update_sigkey
    url = reverse('sigkey-detail', kwargs={'key_id': '1234adbf'})
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 432, in _reverse_with_prefix
    self._populate()
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 284, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/Projects/product-definition-center/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/Projects/product-definition-center/pdc/urls.py", line 13, in <module>
    from pdc.apps.release.views import ReleaseListView, ReleaseDetailView
  File "/home/user/Projects/product-definition-center/pdc/apps/release/views.py", line 10, in <module>
    from kobo.django.views.generic import DetailView, SearchView
ImportError: No module named django.views.generic

----------------------------------------------------------------------
Ran 1065 tests in 4.824s

FAILED (errors=978)
Destroying test database for alias 'default'...
Makefile:21: recipe for target 'test' failed
make: *** [test] Error 1
```

In this second case it looks like the system-wide python library `kobo` can't see django from virtualenv. Workaround for me was to install another copy of `kobo` into virtualenv. After that all django tests passed.
```
$ pip install --upgrade https://git.fedorahosted.org/cgit/kobo.git/snapshot/kobo-0.4.3.tar.gz#egg=kobo
```

**Comment by simozhan** [comment]
@matysek Did you follow option2 in this guide:
https://github.com/product-definition-center/product-definition-center/blob/master/docs/source/development.rst
koji need to be installed first through yum

**Comment by matysek** [comment]
I did not follow option 2. However even when trying the option 2 I still get the same import error:
```
ImportError: No module named django.views.generic
```

**Comment by simozhan** [comment]
@matysek Interesting. To try to produce this issue, i pull and ran a docker image with centos 7. 
As the docker image is light-weight, i installed some necessary packages.
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install python-pip
yum install which
yum install git
yum install gcc
yum install make
yum install python-devel
yum install python-ldap

Then as pdc doc mentioned, 
yum install koji
yum install libxml2-devel libxslt-devel graphviz-devel(these libs are used by the dependencies, it is noted in requirements/devel.txt)
pip install virtualenvwrapper
mkvirtualenv pdc --system-site-packages
then make test, the tests are ok.

So can you tell more detail about your working environment? Maybe i can try on it.

**Comment by simozhan** [comment]
@matysek I think i got the point. There should be already kobo and kobo-rpmlib installed in /usr/lib/python2.7/site-packages/ in your environment, but missing kobo-django. when you installed it again in virtaulenv($ pip install --upgrade https://git.fedorahosted.org/cgit/kobo.git/snapshot/kobo-0.4.3.tar.gz#egg=kobo). The kobo-django will be installed in virtualenv and works.

**Comment by simozhan** [comment]
@matysek have you successfully set up your virtualenv? is my comment useful for you? Or you have fix this yourself. Can i close this ticket?

**Comment by matysek** [comment]
@simozhan you can close it. I successfully set up virtualenv.
